[package]
name = "orion"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.10", features = ["derive"] }
rust-embed = { version="6.4.0", features = ["debug-embed", "compression", "include-exclude"] }
glob = "0.3.0"
gray_matter = "0.2.2"
pulldown-cmark = "0.9.1"
thiserror = "1.0.31"
