base_url: http://adriantombu.github.io/orion/
site_name: Orion
theme: orion
build_path: ./public

robots: index, follow

opengraph:
  type: article

twitter:
  card: summary
  creator: adriantombu
  site: adriantombu
