base_url= "https://adriantombu.github.io/orion/"
site_name = "Orion"
description = "A simple static blog generator made with Rust"
theme = "orion"
build_path = "./public"
locale = "fr_FR"

[seo]
robots = "index, follow"

[twitter]
creator = "adriantombu"
